/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SessionToken = IDL.Text;
export const Result_8 = IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text });
export const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const ArticleInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const Article = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const Result_4 = IDL.Variant({ 'ok' : Article, 'err' : IDL.Text });
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'fileName' : IDL.Opt(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'fileName' : IDL.Opt(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
  'fileUrl' : IDL.Opt(IDL.Text),
});
export const Result_3 = IDL.Variant({ 'ok' : Note, 'err' : IDL.Text });
export const PublicationInput = IDL.Record({
  'doi' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'journal' : IDL.Text,
  'year' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'authors' : IDL.Vec(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'abstract' : IDL.Text,
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const Publication = IDL.Record({
  'id' : IDL.Nat,
  'doi' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'journal' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'authors' : IDL.Vec(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'abstract' : IDL.Text,
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const Result_2 = IDL.Variant({ 'ok' : Publication, 'err' : IDL.Text });
export const ResearchInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const Research = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'pdfUrl' : IDL.Opt(IDL.Text),
  'pdfFileName' : IDL.Opt(IDL.Text),
  'pdfFileId' : IDL.Opt(IDL.Text),
});
export const Result_1 = IDL.Variant({ 'ok' : Research, 'err' : IDL.Text });
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Result_7 = IDL.Variant({
  'ok' : IDL.Vec(ContactSubmission),
  'err' : IDL.Text,
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const UploadResult = IDL.Record({
  'url' : IDL.Text,
  'fileId' : IDL.Text,
});
export const Result = IDL.Variant({ 'ok' : UploadResult, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [Result_8], []),
  'adminLogout' : IDL.Func([IDL.Text], [Result_5], []),
  'createArticle' : IDL.Func([IDL.Text, ArticleInput], [Result_4], []),
  'createArticleWithPdf' : IDL.Func([IDL.Text, ArticleInput], [Result_4], []),
  'createNote' : IDL.Func([IDL.Text, NoteInput], [Result_3], []),
  'createPublication' : IDL.Func([IDL.Text, PublicationInput], [Result_2], []),
  'createPublicationWithPdf' : IDL.Func(
      [IDL.Text, PublicationInput],
      [Result_2],
      [],
    ),
  'createResearch' : IDL.Func([IDL.Text, ResearchInput], [Result_1], []),
  'createResearchWithPdf' : IDL.Func([IDL.Text, ResearchInput], [Result_1], []),
  'deleteArticle' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
  'deleteNote' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
  'deletePdf' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
  'deletePublication' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
  'deleteResearch' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
  'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getContactSubmissions' : IDL.Func([IDL.Text], [Result_7], []),
  'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getPdfUrl' : IDL.Func([IDL.Text], [Result_6], ['query']),
  'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
  'getResearches' : IDL.Func([], [IDL.Vec(Research)], ['query']),
  'markContactRead' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_5], []),
  'updateArticle' : IDL.Func([IDL.Text, IDL.Nat, ArticleInput], [Result_4], []),
  'updateArticleWithPdf' : IDL.Func(
      [IDL.Text, IDL.Nat, ArticleInput],
      [Result_4],
      [],
    ),
  'updateNote' : IDL.Func([IDL.Text, IDL.Nat, NoteInput], [Result_3], []),
  'updatePublication' : IDL.Func(
      [IDL.Text, IDL.Nat, PublicationInput],
      [Result_2],
      [],
    ),
  'updatePublicationWithPdf' : IDL.Func(
      [IDL.Text, IDL.Nat, PublicationInput],
      [Result_2],
      [],
    ),
  'updateResearch' : IDL.Func(
      [IDL.Text, IDL.Nat, ResearchInput],
      [Result_1],
      [],
    ),
  'updateResearchWithPdf' : IDL.Func(
      [IDL.Text, IDL.Nat, ResearchInput],
      [Result_1],
      [],
    ),
  'uploadPdf' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Result],
      [],
    ),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SessionToken = IDL.Text;
  const Result_8 = IDL.Variant({ 'ok' : SessionToken, 'err' : IDL.Text });
  const Result_5 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const ArticleInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const Article = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const Result_4 = IDL.Variant({ 'ok' : Article, 'err' : IDL.Text });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'fileName' : IDL.Opt(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'fileName' : IDL.Opt(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
    'fileUrl' : IDL.Opt(IDL.Text),
  });
  const Result_3 = IDL.Variant({ 'ok' : Note, 'err' : IDL.Text });
  const PublicationInput = IDL.Record({
    'doi' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'journal' : IDL.Text,
    'year' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'authors' : IDL.Vec(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'abstract' : IDL.Text,
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const Publication = IDL.Record({
    'id' : IDL.Nat,
    'doi' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'journal' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'authors' : IDL.Vec(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'abstract' : IDL.Text,
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const Result_2 = IDL.Variant({ 'ok' : Publication, 'err' : IDL.Text });
  const ResearchInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const Research = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'pdfUrl' : IDL.Opt(IDL.Text),
    'pdfFileName' : IDL.Opt(IDL.Text),
    'pdfFileId' : IDL.Opt(IDL.Text),
  });
  const Result_1 = IDL.Variant({ 'ok' : Research, 'err' : IDL.Text });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Result_7 = IDL.Variant({
    'ok' : IDL.Vec(ContactSubmission),
    'err' : IDL.Text,
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UploadResult = IDL.Record({ 'url' : IDL.Text, 'fileId' : IDL.Text });
  const Result = IDL.Variant({ 'ok' : UploadResult, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [Result_8], []),
    'adminLogout' : IDL.Func([IDL.Text], [Result_5], []),
    'createArticle' : IDL.Func([IDL.Text, ArticleInput], [Result_4], []),
    'createArticleWithPdf' : IDL.Func([IDL.Text, ArticleInput], [Result_4], []),
    'createNote' : IDL.Func([IDL.Text, NoteInput], [Result_3], []),
    'createPublication' : IDL.Func(
        [IDL.Text, PublicationInput],
        [Result_2],
        [],
      ),
    'createPublicationWithPdf' : IDL.Func(
        [IDL.Text, PublicationInput],
        [Result_2],
        [],
      ),
    'createResearch' : IDL.Func([IDL.Text, ResearchInput], [Result_1], []),
    'createResearchWithPdf' : IDL.Func(
        [IDL.Text, ResearchInput],
        [Result_1],
        [],
      ),
    'deleteArticle' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
    'deleteNote' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
    'deletePdf' : IDL.Func([IDL.Text, IDL.Text], [Result_5], []),
    'deletePublication' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
    'deleteResearch' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
    'getArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getContactSubmissions' : IDL.Func([IDL.Text], [Result_7], []),
    'getNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getPdfUrl' : IDL.Func([IDL.Text], [Result_6], ['query']),
    'getPublications' : IDL.Func([], [IDL.Vec(Publication)], ['query']),
    'getResearches' : IDL.Func([], [IDL.Vec(Research)], ['query']),
    'markContactRead' : IDL.Func([IDL.Text, IDL.Nat], [Result_5], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Result_5], []),
    'updateArticle' : IDL.Func(
        [IDL.Text, IDL.Nat, ArticleInput],
        [Result_4],
        [],
      ),
    'updateArticleWithPdf' : IDL.Func(
        [IDL.Text, IDL.Nat, ArticleInput],
        [Result_4],
        [],
      ),
    'updateNote' : IDL.Func([IDL.Text, IDL.Nat, NoteInput], [Result_3], []),
    'updatePublication' : IDL.Func(
        [IDL.Text, IDL.Nat, PublicationInput],
        [Result_2],
        [],
      ),
    'updatePublicationWithPdf' : IDL.Func(
        [IDL.Text, IDL.Nat, PublicationInput],
        [Result_2],
        [],
      ),
    'updateResearch' : IDL.Func(
        [IDL.Text, IDL.Nat, ResearchInput],
        [Result_1],
        [],
      ),
    'updateResearchWithPdf' : IDL.Func(
        [IDL.Text, IDL.Nat, ResearchInput],
        [Result_1],
        [],
      ),
    'uploadPdf' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Result],
        [],
      ),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };