/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'pdfUrl' : [] | [string],
  'excerpt' : string,
  'category' : string,
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
}
export interface ArticleInput {
  'title' : string,
  'content' : string,
  'date' : string,
  'tags' : Array<string>,
  'pdfUrl' : [] | [string],
  'excerpt' : string,
  'category' : string,
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
}
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'submittedAt' : bigint,
  'isRead' : boolean,
  'email' : string,
  'message' : string,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
  'fileName' : [] | [string],
  'pdfUrl' : [] | [string],
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
  'fileUrl' : [] | [string],
}
export interface NoteInput {
  'title' : string,
  'content' : string,
  'fileName' : [] | [string],
  'pdfUrl' : [] | [string],
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
  'fileUrl' : [] | [string],
}
export interface Publication {
  'id' : bigint,
  'doi' : [] | [string],
  'title' : string,
  'journal' : string,
  'createdAt' : bigint,
  'year' : bigint,
  'imageUrl' : [] | [string],
  'authors' : Array<string>,
  'pdfUrl' : [] | [string],
  'abstract' : string,
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
}
export interface PublicationInput {
  'doi' : [] | [string],
  'title' : string,
  'journal' : string,
  'year' : bigint,
  'imageUrl' : [] | [string],
  'authors' : Array<string>,
  'pdfUrl' : [] | [string],
  'abstract' : string,
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
}
export interface Research {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'summary' : string,
  'imageUrl' : [] | [string],
  'pdfUrl' : [] | [string],
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
}
export interface ResearchInput {
  'title' : string,
  'date' : string,
  'tags' : Array<string>,
  'description' : string,
  'summary' : string,
  'imageUrl' : [] | [string],
  'pdfUrl' : [] | [string],
  'pdfFileName' : [] | [string],
  'pdfFileId' : [] | [string],
}
export type Result = { 'ok' : UploadResult } |
  { 'err' : string };
export type Result_1 = { 'ok' : Research } |
  { 'err' : string };
export type Result_2 = { 'ok' : Publication } |
  { 'err' : string };
export type Result_3 = { 'ok' : Note } |
  { 'err' : string };
export type Result_4 = { 'ok' : Article } |
  { 'err' : string };
export type Result_5 = { 'ok' : null } |
  { 'err' : string };
export type Result_6 = { 'ok' : string } |
  { 'err' : string };
export type Result_7 = { 'ok' : Array<ContactSubmission> } |
  { 'err' : string };
export type Result_8 = { 'ok' : SessionToken } |
  { 'err' : string };
export type SessionToken = string;
export interface UploadResult { 'url' : string, 'fileId' : string }
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminLogin' : ActorMethod<[string, string], Result_8>,
  'adminLogout' : ActorMethod<[string], Result_5>,
  'createArticle' : ActorMethod<[string, ArticleInput], Result_4>,
  'createArticleWithPdf' : ActorMethod<[string, ArticleInput], Result_4>,
  'createNote' : ActorMethod<[string, NoteInput], Result_3>,
  'createPublication' : ActorMethod<[string, PublicationInput], Result_2>,
  'createPublicationWithPdf' : ActorMethod<
    [string, PublicationInput],
    Result_2
  >,
  'createResearch' : ActorMethod<[string, ResearchInput], Result_1>,
  'createResearchWithPdf' : ActorMethod<[string, ResearchInput], Result_1>,
  'deleteArticle' : ActorMethod<[string, bigint], Result_5>,
  'deleteNote' : ActorMethod<[string, bigint], Result_5>,
  'deletePdf' : ActorMethod<[string, string], Result_5>,
  'deletePublication' : ActorMethod<[string, bigint], Result_5>,
  'deleteResearch' : ActorMethod<[string, bigint], Result_5>,
  'getArticles' : ActorMethod<[], Array<Article>>,
  'getContactSubmissions' : ActorMethod<[string], Result_7>,
  'getNotes' : ActorMethod<[], Array<Note>>,
  'getPdfUrl' : ActorMethod<[string], Result_6>,
  'getPublications' : ActorMethod<[], Array<Publication>>,
  'getResearches' : ActorMethod<[], Array<Research>>,
  'markContactRead' : ActorMethod<[string, bigint], Result_5>,
  'submitContact' : ActorMethod<[string, string, string], Result_5>,
  'updateArticle' : ActorMethod<[string, bigint, ArticleInput], Result_4>,
  'updateArticleWithPdf' : ActorMethod<
    [string, bigint, ArticleInput],
    Result_4
  >,
  'updateNote' : ActorMethod<[string, bigint, NoteInput], Result_3>,
  'updatePublication' : ActorMethod<
    [string, bigint, PublicationInput],
    Result_2
  >,
  'updatePublicationWithPdf' : ActorMethod<
    [string, bigint, PublicationInput],
    Result_2
  >,
  'updateResearch' : ActorMethod<[string, bigint, ResearchInput], Result_1>,
  'updateResearchWithPdf' : ActorMethod<
    [string, bigint, ResearchInput],
    Result_1
  >,
  'uploadPdf' : ActorMethod<[string, string, string, string], Result>,
  'validateSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];