/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Article {
    id: bigint;
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
    category: string;
    pdfFileName?: string;
    pdfFileId?: string;
}
export type Result_2 = {
    __kind__: "ok";
    ok: Publication;
} | {
    __kind__: "err";
    err: string;
};
export interface PublicationInput {
    doi?: string;
    title: string;
    journal: string;
    year: bigint;
    imageUrl?: string;
    authors: Array<string>;
    pdfUrl?: string;
    abstract: string;
    pdfFileName?: string;
    pdfFileId?: string;
}
export type Result_6 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ContactSubmission {
    id: bigint;
    name: string;
    submittedAt: bigint;
    isRead: boolean;
    email: string;
    message: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: Research;
} | {
    __kind__: "err";
    err: string;
};
export interface UploadResult {
    url: string;
    fileId: string;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Article;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: UploadResult;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "err";
    err: string;
};
export interface NoteInput {
    title: string;
    content: string;
    fileName?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
    fileUrl?: string;
}
export type SessionToken = string;
export type Result_8 = {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
};
export type Result_7 = {
    __kind__: "ok";
    ok: Array<ContactSubmission>;
} | {
    __kind__: "err";
    err: string;
};
export interface Publication {
    id: bigint;
    doi?: string;
    title: string;
    journal: string;
    createdAt: bigint;
    year: bigint;
    imageUrl?: string;
    authors: Array<string>;
    pdfUrl?: string;
    abstract: string;
    pdfFileName?: string;
    pdfFileId?: string;
}
export interface ArticleInput {
    title: string;
    content: string;
    date: string;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
    category: string;
    pdfFileName?: string;
    pdfFileId?: string;
}
export interface Research {
    id: bigint;
    title: string;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    summary: string;
    imageUrl?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
}
export interface ResearchInput {
    title: string;
    date: string;
    tags: Array<string>;
    description: string;
    summary: string;
    imageUrl?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
}
export interface Note {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    fileName?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
    fileUrl?: string;
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    adminLogin(username: string, password: string): Promise<Result_8>;
    adminLogout(token: string): Promise<Result_5>;
    createArticle(token: string, input: ArticleInput): Promise<Result_4>;
    createArticleWithPdf(token: string, input: ArticleInput): Promise<Result_4>;
    createNote(token: string, input: NoteInput): Promise<Result_3>;
    createPublication(token: string, input: PublicationInput): Promise<Result_2>;
    createPublicationWithPdf(token: string, input: PublicationInput): Promise<Result_2>;
    createResearch(token: string, input: ResearchInput): Promise<Result_1>;
    createResearchWithPdf(token: string, input: ResearchInput): Promise<Result_1>;
    deleteArticle(token: string, id: bigint): Promise<Result_5>;
    deleteNote(token: string, id: bigint): Promise<Result_5>;
    deletePdf(token: string, fileId: string): Promise<Result_5>;
    deletePublication(token: string, id: bigint): Promise<Result_5>;
    deleteResearch(token: string, id: bigint): Promise<Result_5>;
    getArticles(): Promise<Array<Article>>;
    getContactSubmissions(token: string): Promise<Result_7>;
    getNotes(): Promise<Array<Note>>;
    getPdfUrl(fileId: string): Promise<Result_6>;
    getPublications(): Promise<Array<Publication>>;
    getResearches(): Promise<Array<Research>>;
    markContactRead(token: string, id: bigint): Promise<Result_5>;
    submitContact(name: string, email: string, message: string): Promise<Result_5>;
    updateArticle(token: string, id: bigint, input: ArticleInput): Promise<Result_4>;
    updateArticleWithPdf(token: string, id: bigint, input: ArticleInput): Promise<Result_4>;
    updateNote(token: string, id: bigint, input: NoteInput): Promise<Result_3>;
    updatePublication(token: string, id: bigint, input: PublicationInput): Promise<Result_2>;
    updatePublicationWithPdf(token: string, id: bigint, input: PublicationInput): Promise<Result_2>;
    updateResearch(token: string, id: bigint, input: ResearchInput): Promise<Result_1>;
    updateResearchWithPdf(token: string, id: bigint, input: ResearchInput): Promise<Result_1>;
    uploadPdf(token: string, fileName: string, contentType: string, fileId: string): Promise<Result>;
    validateSession(token: string): Promise<boolean>;
}
import type { Article as _Article, ArticleInput as _ArticleInput, ContactSubmission as _ContactSubmission, Note as _Note, NoteInput as _NoteInput, Publication as _Publication, PublicationInput as _PublicationInput, Research as _Research, ResearchInput as _ResearchInput, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, Result_7 as _Result_7, Result_8 as _Result_8, SessionToken as _SessionToken, UploadResult as _UploadResult, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<Result_8> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_Result_8_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_Result_8_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async createArticle(arg0: string, arg1: ArticleInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticle(arg0, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticle(arg0, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createArticleWithPdf(arg0: string, arg1: ArticleInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.createArticleWithPdf(arg0, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createArticleWithPdf(arg0, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async createNote(arg0: string, arg1: NoteInput): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, to_candid_NoteInput_n19(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, to_candid_NoteInput_n19(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPublication(arg0: string, arg1: PublicationInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublication(arg0, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublication(arg0, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async createPublicationWithPdf(arg0: string, arg1: PublicationInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.createPublicationWithPdf(arg0, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPublicationWithPdf(arg0, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async createResearch(arg0: string, arg1: ResearchInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createResearch(arg0, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResearch(arg0, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async createResearchWithPdf(arg0: string, arg1: ResearchInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.createResearchWithPdf(arg0, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResearchWithPdf(arg0, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteArticle(arg0: string, arg1: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0, arg1);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0, arg1);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteNote(arg0: string, arg1: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0, arg1);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0, arg1);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePdf(arg0: string, arg1: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePdf(arg0, arg1);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePdf(arg0, arg1);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deletePublication(arg0: string, arg1: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePublication(arg0, arg1);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePublication(arg0, arg1);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteResearch(arg0: string, arg1: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResearch(arg0, arg1);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResearch(arg0, arg1);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticles();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticles();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(arg0: string): Promise<Result_7> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions(arg0);
                return from_candid_Result_7_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions(arg0);
            return from_candid_Result_7_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotes();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotes();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPdfUrl(arg0: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.getPdfUrl(arg0);
                return from_candid_Result_6_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPdfUrl(arg0);
            return from_candid_Result_6_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublications(): Promise<Array<Publication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublications();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublications();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearches(): Promise<Array<Research>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearches();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearches();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async markContactRead(arg0: string, arg1: bigint): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactRead(arg0, arg1);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactRead(arg0, arg1);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2);
                return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2);
            return from_candid_Result_5_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArticle(arg0: string, arg1: bigint, arg2: ArticleInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticle(arg0, arg1, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticle(arg0, arg1, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateArticleWithPdf(arg0: string, arg1: bigint, arg2: ArticleInput): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticleWithPdf(arg0, arg1, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticleWithPdf(arg0, arg1, to_candid_ArticleInput_n12(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_4_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNote(arg0: string, arg1: bigint, arg2: NoteInput): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, to_candid_NoteInput_n19(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, to_candid_NoteInput_n19(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_3_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePublication(arg0: string, arg1: bigint, arg2: PublicationInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublication(arg0, arg1, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublication(arg0, arg1, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePublicationWithPdf(arg0: string, arg1: bigint, arg2: PublicationInput): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePublicationWithPdf(arg0, arg1, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePublicationWithPdf(arg0, arg1, to_candid_PublicationInput_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_2_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResearch(arg0: string, arg1: bigint, arg2: ResearchInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResearch(arg0, arg1, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResearch(arg0, arg1, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateResearchWithPdf(arg0: string, arg1: bigint, arg2: ResearchInput): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResearchWithPdf(arg0, arg1, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResearchWithPdf(arg0, arg1, to_candid_ResearchInput_n31(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Result_1_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPdf(arg0: string, arg1: string, arg2: string, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPdf(arg0, arg1, arg2, arg3);
                return from_candid_Result_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPdf(arg0, arg1, arg2, arg3);
            return from_candid_Result_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return result;
        }
    }
}
function from_candid_Article_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Article {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Note_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Note): Note {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Publication_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Publication): Publication {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Research_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Research): Research {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Result_6_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Result_6 {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_Result_7_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_7): Result_7 {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Result_8_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_8): Result_8 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    pdfUrl: [] | [string];
    excerpt: string;
    category: string;
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
}): {
    id: bigint;
    title: string;
    content: string;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
    category: string;
    pdfFileName?: string;
    pdfFileId?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        createdAt: value.createdAt,
        tags: value.tags,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfUrl)),
        excerpt: value.excerpt,
        category: value.category,
        pdfFileName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileName)),
        pdfFileId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileId))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    fileName: [] | [string];
    pdfUrl: [] | [string];
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
    fileUrl: [] | [string];
}): {
    id: bigint;
    title: string;
    content: string;
    createdAt: bigint;
    fileName?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
    fileUrl?: string;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        fileName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.fileName)),
        pdfUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfUrl)),
        pdfFileName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileName)),
        pdfFileId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileId)),
        fileUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.fileUrl))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    doi: [] | [string];
    title: string;
    journal: string;
    createdAt: bigint;
    year: bigint;
    imageUrl: [] | [string];
    authors: Array<string>;
    pdfUrl: [] | [string];
    abstract: string;
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
}): {
    id: bigint;
    doi?: string;
    title: string;
    journal: string;
    createdAt: bigint;
    year: bigint;
    imageUrl?: string;
    authors: Array<string>;
    pdfUrl?: string;
    abstract: string;
    pdfFileName?: string;
    pdfFileId?: string;
} {
    return {
        id: value.id,
        doi: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.doi)),
        title: value.title,
        journal: value.journal,
        createdAt: value.createdAt,
        year: value.year,
        imageUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.imageUrl)),
        authors: value.authors,
        pdfUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfUrl)),
        abstract: value.abstract,
        pdfFileName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileName)),
        pdfFileId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileId))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    summary: string;
    imageUrl: [] | [string];
    pdfUrl: [] | [string];
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
}): {
    id: bigint;
    title: string;
    date: string;
    createdAt: bigint;
    tags: Array<string>;
    description: string;
    summary: string;
    imageUrl?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
} {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        summary: value.summary,
        imageUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.imageUrl)),
        pdfUrl: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfUrl)),
        pdfFileName: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileName)),
        pdfFileId: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.pdfFileId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Article;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Article;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Article_n16(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Note;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Note;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Note_n23(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Publication;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Publication;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Publication_n29(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Research;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Research;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Research_n35(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ContactSubmission>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ContactSubmission>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UploadResult;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UploadResult;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SessionToken;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SessionToken;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Array<Article> {
    return value.map((x)=>from_candid_Article_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Note>): Array<Note> {
    return value.map((x)=>from_candid_Note_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Publication>): Array<Publication> {
    return value.map((x)=>from_candid_Publication_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Research>): Array<Research> {
    return value.map((x)=>from_candid_Research_n35(_uploadFile, _downloadFile, x));
}
function to_candid_ArticleInput_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArticleInput): _ArticleInput {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_NoteInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NoteInput): _NoteInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PublicationInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PublicationInput): _PublicationInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_ResearchInput_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchInput): _ResearchInput {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    date: string;
    tags: Array<string>;
    pdfUrl?: string;
    excerpt: string;
    category: string;
    pdfFileName?: string;
    pdfFileId?: string;
}): {
    title: string;
    content: string;
    date: string;
    tags: Array<string>;
    pdfUrl: [] | [string];
    excerpt: string;
    category: string;
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
} {
    return {
        title: value.title,
        content: value.content,
        date: value.date,
        tags: value.tags,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        excerpt: value.excerpt,
        category: value.category,
        pdfFileName: value.pdfFileName ? candid_some(value.pdfFileName) : candid_none(),
        pdfFileId: value.pdfFileId ? candid_some(value.pdfFileId) : candid_none()
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    content: string;
    fileName?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
    fileUrl?: string;
}): {
    title: string;
    content: string;
    fileName: [] | [string];
    pdfUrl: [] | [string];
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
    fileUrl: [] | [string];
} {
    return {
        title: value.title,
        content: value.content,
        fileName: value.fileName ? candid_some(value.fileName) : candid_none(),
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        pdfFileName: value.pdfFileName ? candid_some(value.pdfFileName) : candid_none(),
        pdfFileId: value.pdfFileId ? candid_some(value.pdfFileId) : candid_none(),
        fileUrl: value.fileUrl ? candid_some(value.fileUrl) : candid_none()
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doi?: string;
    title: string;
    journal: string;
    year: bigint;
    imageUrl?: string;
    authors: Array<string>;
    pdfUrl?: string;
    abstract: string;
    pdfFileName?: string;
    pdfFileId?: string;
}): {
    doi: [] | [string];
    title: string;
    journal: string;
    year: bigint;
    imageUrl: [] | [string];
    authors: Array<string>;
    pdfUrl: [] | [string];
    abstract: string;
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
} {
    return {
        doi: value.doi ? candid_some(value.doi) : candid_none(),
        title: value.title,
        journal: value.journal,
        year: value.year,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        authors: value.authors,
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        abstract: value.abstract,
        pdfFileName: value.pdfFileName ? candid_some(value.pdfFileName) : candid_none(),
        pdfFileId: value.pdfFileId ? candid_some(value.pdfFileId) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    tags: Array<string>;
    description: string;
    summary: string;
    imageUrl?: string;
    pdfUrl?: string;
    pdfFileName?: string;
    pdfFileId?: string;
}): {
    title: string;
    date: string;
    tags: Array<string>;
    description: string;
    summary: string;
    imageUrl: [] | [string];
    pdfUrl: [] | [string];
    pdfFileName: [] | [string];
    pdfFileId: [] | [string];
} {
    return {
        title: value.title,
        date: value.date,
        tags: value.tags,
        description: value.description,
        summary: value.summary,
        imageUrl: value.imageUrl ? candid_some(value.imageUrl) : candid_none(),
        pdfUrl: value.pdfUrl ? candid_some(value.pdfUrl) : candid_none(),
        pdfFileName: value.pdfFileName ? candid_some(value.pdfFileName) : candid_none(),
        pdfFileId: value.pdfFileId ? candid_some(value.pdfFileId) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
